/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Fri Apr 19 00:07:30 CST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkTestDriver_h__
#define __mkTestDriver_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkMultiplier.h"


/* Class declaration for the mkTestDriver module */
class MOD_mkTestDriver : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_m_doneread;
  MOD_Reg<tUInt8> INST_m_doneread_double_write_error;
  MOD_Reg<tUInt32> INST_m_in;
  MOD_Reg<tUInt8> INST_m_in_double_write_error;
  MOD_Reg<tUInt8> INST_m_inited;
  MOD_Reg<tUInt8> INST_m_inited_double_write_error;
  MOD_Reg<tUInt32> INST_m_out;
  MOD_Reg<tUInt8> INST_m_out_double_write_error;
  MOD_Counter<tUInt32> INST_m_outstanding;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index;
  MOD_Reg<tUInt8> INST_pipeline_chunker_index_double_write_error;
  MOD_Fifo<tUInt64> INST_pipeline_chunker_infifo;
  MOD_Fifo<tUWide> INST_pipeline_chunker_outfifo;
  MOD_Reg<tUWide> INST_pipeline_chunker_pending;
  MOD_Reg<tUInt8> INST_pipeline_chunker_pending_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_fft_fft_outputFIFO;
  MOD_Fifo<tUInt32> INST_pipeline_fir_infifo;
  MOD_mkMultiplier INST_pipeline_fir_m_0;
  MOD_mkMultiplier INST_pipeline_fir_m_1;
  MOD_mkMultiplier INST_pipeline_fir_m_2;
  MOD_mkMultiplier INST_pipeline_fir_m_3;
  MOD_mkMultiplier INST_pipeline_fir_m_4;
  MOD_mkMultiplier INST_pipeline_fir_m_5;
  MOD_mkMultiplier INST_pipeline_fir_m_6;
  MOD_mkMultiplier INST_pipeline_fir_m_7;
  MOD_mkMultiplier INST_pipeline_fir_m_8;
  MOD_Fifo<tUInt32> INST_pipeline_fir_outfifo;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_0;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_0_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_1;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_1_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_2;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_2_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_3;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_3_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_4;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_4_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_5;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_5_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_6;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_6_double_write_error;
  MOD_Reg<tUInt32> INST_pipeline_fir_r_7;
  MOD_Reg<tUInt8> INST_pipeline_fir_r_7_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_inputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_ifft_fft_fft_outputFIFO;
  MOD_Fifo<tUWide> INST_pipeline_ifft_outfifo;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index;
  MOD_Reg<tUInt8> INST_pipeline_splitter_index_double_write_error;
  MOD_Fifo<tUWide> INST_pipeline_splitter_infifo;
  MOD_Fifo<tUInt64> INST_pipeline_splitter_outfifo;
 
 /* Constructor */
 public:
  MOD_mkTestDriver(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_finish;
  tUInt8 DEF_CAN_FIRE_RL_finish;
  tUInt8 DEF_WILL_FIRE_RL_write;
  tUInt8 DEF_CAN_FIRE_RL_write;
  tUInt8 DEF_WILL_FIRE_RL_pad;
  tUInt8 DEF_CAN_FIRE_RL_pad;
  tUInt8 DEF_WILL_FIRE_RL_read;
  tUInt8 DEF_CAN_FIRE_RL_read;
  tUInt8 DEF_WILL_FIRE_RL_init;
  tUInt8 DEF_CAN_FIRE_RL_init;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_to_splitter;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_to_splitter;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_to_ifft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_to_ifft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_to_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_to_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_to_chunker;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_splitter_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_inversify;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_ifft_fft_fft_comb_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_ifft_fft_fft_comb_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fft_fft_comb_fft;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fft_fft_comb_fft;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_chunker_iterate;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_add;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_add;
  tUInt8 DEF_WILL_FIRE_RL_pipeline_fir_mult;
  tUInt8 DEF_CAN_FIRE_RL_pipeline_fir_mult;
  tUInt8 DEF_x__h7785;
  tUInt8 DEF_pipeline_chunker_index_4_EQ_7___d85;
 
 /* Local definitions */
 private:
  tUInt32 DEF_b__h626580;
  tUInt32 DEF_x__h626738;
  tUInt32 DEF_TASK_fopen___d2396;
  tUInt32 DEF_TASK_fopen___d2394;
  tUWide DEF_pipeline_splitter_infifo_first____d2299;
  tUWide DEF_pipeline_ifft_outfifo_first____d2385;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first____d2254;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first____d1190;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first____d2369;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first____d126;
  tUWide DEF_pipeline_chunker_pending__h8709;
  tUWide DEF_pipeline_chunker_outfifo_first____d2353;
  tUInt32 DEF_m_out___d2425;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__369_BITS_51_ETC___d2381;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__369_BITS_51_ETC___d2378;
  tUWide DEF_pipeline_chunker_outfifo_first__353_BITS_511_T_ETC___d2365;
  tUWide DEF_pipeline_chunker_outfifo_first__353_BITS_511_T_ETC___d2362;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__254_BI_ETC___d2293;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__254_BI_ETC___d2283;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first__190_BIT_ETC___d2250;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first__190_BIT_ETC___d2244;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d121;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d114;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first__26_BITS_63_T_ETC___d1186;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first__26_BITS_63_T_ETC___d1180;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__369_BITS_51_ETC___d2375;
  tUWide DEF_pipeline_chunker_outfifo_first__353_BITS_511_T_ETC___d2359;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__254_BI_ETC___d2273;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first__190_BIT_ETC___d2238;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d107;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first__26_BITS_63_T_ETC___d1174;
  tUWide DEF_pipeline_fft_fft_outputFIFO_first__369_BITS_51_ETC___d2372;
  tUWide DEF_pipeline_chunker_outfifo_first__353_BITS_511_T_ETC___d2356;
  tUWide DEF_pipeline_ifft_fft_fft_outputFIFO_first__254_BI_ETC___d2263;
  tUWide DEF_pipeline_ifft_fft_fft_inputFIFO_first__190_BIT_ETC___d2000;
  tUWide DEF_IF_pipeline_chunker_index_4_EQ_7_5_THEN_pipeli_ETC___d100;
  tUWide DEF_pipeline_fft_fft_inputFIFO_first__26_BITS_63_T_ETC___d936;
 
 /* Rules */
 public:
  void RL_pipeline_fir_mult();
  void RL_pipeline_fir_add();
  void RL_pipeline_chunker_iterate();
  void RL_pipeline_fft_fft_comb_fft();
  void RL_pipeline_ifft_fft_fft_comb_fft();
  void RL_pipeline_ifft_inversify();
  void RL_pipeline_splitter_iterate();
  void RL_pipeline_fir_to_chunker();
  void RL_pipeline_chunker_to_fft();
  void RL_pipeline_fft_to_ifft();
  void RL_pipeline_ifft_to_splitter();
  void RL_init();
  void RL_read();
  void RL_pad();
  void RL_write();
  void RL_finish();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTestDriver &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTestDriver &backing);
};

#endif /* ifndef __mkTestDriver_h__ */
