/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Mon Mar 11 00:47:43 CST 2024
 * 
 */

/* Generation options: */
#ifndef __mkFftCombinational_h__
#define __mkFftCombinational_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftCombinational module */
class MOD_mkFftCombinational : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0_0;
  MOD_mkBfly4 INST_bfly_0_1;
  MOD_mkBfly4 INST_bfly_0_10;
  MOD_mkBfly4 INST_bfly_0_11;
  MOD_mkBfly4 INST_bfly_0_12;
  MOD_mkBfly4 INST_bfly_0_13;
  MOD_mkBfly4 INST_bfly_0_14;
  MOD_mkBfly4 INST_bfly_0_15;
  MOD_mkBfly4 INST_bfly_0_2;
  MOD_mkBfly4 INST_bfly_0_3;
  MOD_mkBfly4 INST_bfly_0_4;
  MOD_mkBfly4 INST_bfly_0_5;
  MOD_mkBfly4 INST_bfly_0_6;
  MOD_mkBfly4 INST_bfly_0_7;
  MOD_mkBfly4 INST_bfly_0_8;
  MOD_mkBfly4 INST_bfly_0_9;
  MOD_mkBfly4 INST_bfly_1_0;
  MOD_mkBfly4 INST_bfly_1_1;
  MOD_mkBfly4 INST_bfly_1_10;
  MOD_mkBfly4 INST_bfly_1_11;
  MOD_mkBfly4 INST_bfly_1_12;
  MOD_mkBfly4 INST_bfly_1_13;
  MOD_mkBfly4 INST_bfly_1_14;
  MOD_mkBfly4 INST_bfly_1_15;
  MOD_mkBfly4 INST_bfly_1_2;
  MOD_mkBfly4 INST_bfly_1_3;
  MOD_mkBfly4 INST_bfly_1_4;
  MOD_mkBfly4 INST_bfly_1_5;
  MOD_mkBfly4 INST_bfly_1_6;
  MOD_mkBfly4 INST_bfly_1_7;
  MOD_mkBfly4 INST_bfly_1_8;
  MOD_mkBfly4 INST_bfly_1_9;
  MOD_mkBfly4 INST_bfly_2_0;
  MOD_mkBfly4 INST_bfly_2_1;
  MOD_mkBfly4 INST_bfly_2_10;
  MOD_mkBfly4 INST_bfly_2_11;
  MOD_mkBfly4 INST_bfly_2_12;
  MOD_mkBfly4 INST_bfly_2_13;
  MOD_mkBfly4 INST_bfly_2_14;
  MOD_mkBfly4 INST_bfly_2_15;
  MOD_mkBfly4 INST_bfly_2_2;
  MOD_mkBfly4 INST_bfly_2_3;
  MOD_mkBfly4 INST_bfly_2_4;
  MOD_mkBfly4 INST_bfly_2_5;
  MOD_mkBfly4 INST_bfly_2_6;
  MOD_mkBfly4 INST_bfly_2_7;
  MOD_mkBfly4 INST_bfly_2_8;
  MOD_mkBfly4 INST_bfly_2_9;
  MOD_Fifo<tUWide> INST_inFifo;
  MOD_Fifo<tUWide> INST_outFifo;
 
 /* Constructor */
 public:
  MOD_mkFftCombinational(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_inFifo_first____d4;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d356;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d353;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d350;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d347;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d344;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d341;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d338;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d335;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d332;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d329;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d326;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d323;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d320;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d317;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d314;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d311;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d308;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d298;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d288;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d278;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d268;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d258;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d248;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d238;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d228;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d204;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d180;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d156;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d132;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_bfly_1_15__ETC___d100;
  tUWide DEF_deq__avValue1;
 
 /* Rules */
 public:
  void RL_doFft();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftCombinational &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftCombinational &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftCombinational &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftCombinational &backing);
};

#endif /* ifndef __mkFftCombinational_h__ */
