/*
 * Generated by Bluespec Compiler (build 14ff62d)
 * 
 * On Mon Mar 11 00:21:47 CST 2024
 * 
 */

/* Generation options: */
#ifndef __mkFftInelasticPipeline_h__
#define __mkFftInelasticPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkBfly4.h"


/* Class declaration for the mkFftInelasticPipeline module */
class MOD_mkFftInelasticPipeline : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkBfly4 INST_bfly_0_0;
  MOD_mkBfly4 INST_bfly_0_1;
  MOD_mkBfly4 INST_bfly_0_10;
  MOD_mkBfly4 INST_bfly_0_11;
  MOD_mkBfly4 INST_bfly_0_12;
  MOD_mkBfly4 INST_bfly_0_13;
  MOD_mkBfly4 INST_bfly_0_14;
  MOD_mkBfly4 INST_bfly_0_15;
  MOD_mkBfly4 INST_bfly_0_2;
  MOD_mkBfly4 INST_bfly_0_3;
  MOD_mkBfly4 INST_bfly_0_4;
  MOD_mkBfly4 INST_bfly_0_5;
  MOD_mkBfly4 INST_bfly_0_6;
  MOD_mkBfly4 INST_bfly_0_7;
  MOD_mkBfly4 INST_bfly_0_8;
  MOD_mkBfly4 INST_bfly_0_9;
  MOD_mkBfly4 INST_bfly_1_0;
  MOD_mkBfly4 INST_bfly_1_1;
  MOD_mkBfly4 INST_bfly_1_10;
  MOD_mkBfly4 INST_bfly_1_11;
  MOD_mkBfly4 INST_bfly_1_12;
  MOD_mkBfly4 INST_bfly_1_13;
  MOD_mkBfly4 INST_bfly_1_14;
  MOD_mkBfly4 INST_bfly_1_15;
  MOD_mkBfly4 INST_bfly_1_2;
  MOD_mkBfly4 INST_bfly_1_3;
  MOD_mkBfly4 INST_bfly_1_4;
  MOD_mkBfly4 INST_bfly_1_5;
  MOD_mkBfly4 INST_bfly_1_6;
  MOD_mkBfly4 INST_bfly_1_7;
  MOD_mkBfly4 INST_bfly_1_8;
  MOD_mkBfly4 INST_bfly_1_9;
  MOD_mkBfly4 INST_bfly_2_0;
  MOD_mkBfly4 INST_bfly_2_1;
  MOD_mkBfly4 INST_bfly_2_10;
  MOD_mkBfly4 INST_bfly_2_11;
  MOD_mkBfly4 INST_bfly_2_12;
  MOD_mkBfly4 INST_bfly_2_13;
  MOD_mkBfly4 INST_bfly_2_14;
  MOD_mkBfly4 INST_bfly_2_15;
  MOD_mkBfly4 INST_bfly_2_2;
  MOD_mkBfly4 INST_bfly_2_3;
  MOD_mkBfly4 INST_bfly_2_4;
  MOD_mkBfly4 INST_bfly_2_5;
  MOD_mkBfly4 INST_bfly_2_6;
  MOD_mkBfly4 INST_bfly_2_7;
  MOD_mkBfly4 INST_bfly_2_8;
  MOD_mkBfly4 INST_bfly_2_9;
  MOD_Fifo<tUWide> INST_inFifo;
  MOD_Fifo<tUWide> INST_outFifo;
  MOD_Reg<tUWide> INST_sReg1;
  MOD_Reg<tUWide> INST_sReg2;
 
 /* Constructor */
 public:
  MOD_mkFftInelasticPipeline(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_in;
  tUWide PORT_deq;
 
 /* Publicly accessible definitions */
 public:
  tUWide DEF_sReg2___d5;
  tUInt8 DEF_inFifo_notEmpty____d1;
  tUInt8 DEF_sReg2_BIT_1024___d6;
 
 /* Local definitions */
 private:
  tUWide DEF_sReg1___d142;
  tUWide DEF_inFifo_first____d11;
  tUWide DEF_IF_sReg1_42_BIT_1024_43_THEN_bfly_1_15_bfly4_2_ETC___d288;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d287;
  tUWide DEF_IF_inFifo_notEmpty_THEN_bfly_0_15_bfly4_225155_ETC___d140;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d139;
  tUWide DEF_sReg1_42_BIT_1024_43_CONCAT_IF_sReg1_42_BIT_10_ETC___d289;
  tUWide DEF_inFifo_notEmpty_CONCAT_IF_inFifo_notEmpty_THEN_ETC___d141;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d433;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d430;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d136;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d284;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d427;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d281;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d133;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d424;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d130;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d278;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d421;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d127;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d275;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d418;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d124;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d272;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d415;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d121;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d269;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d412;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d118;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d266;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d409;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d115;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d263;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d406;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d112;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d260;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d403;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d109;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d257;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d400;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d106;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d254;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d397;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d103;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d251;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d394;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d100;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d248;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d391;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d97;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d245;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d388;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d94;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d242;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d385;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d91;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d239;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d379;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d86;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d233;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d373;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d81;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d227;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d367;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d76;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d221;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d361;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d71;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d215;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d355;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d66;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d209;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d349;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d61;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d203;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d343;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d56;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d197;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d337;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d51;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d191;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d331;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d46;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d185;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d325;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d41;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d179;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d319;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d36;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d173;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d313;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d31;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d167;
  tUWide DEF_bfly_2_15_bfly4_2251552690364292668_IF_sReg2_B_ETC___d307;
  tUWide DEF_bfly_0_15_bfly4_2251552690364292668_inFifo_fir_ETC___d26;
  tUWide DEF_bfly_1_15_bfly4_2251552690364292668_IF_sReg1_4_ETC___d161;
  tUWide DEF_deq__avValue1;
 
 /* Rules */
 public:
  void RL_doFft();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_in);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq();
  tUInt8 METH_RDY_deq();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFftInelasticPipeline &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFftInelasticPipeline &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFftInelasticPipeline &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFftInelasticPipeline &backing);
};

#endif /* ifndef __mkFftInelasticPipeline_h__ */
